Fix build error with UCONFIG_NO_FORMATTING=1
When building with `UCONFIG_NO_FORMATTING=1`, the following compiler error occurs in the `FormattedListBuilder` class:

```
../source/i18n/listformatter.cpp:570:24: error: allocation of incomplete type 'icu_68::FormattedListData'
            : data(new FormattedListData(status), status) {
                       ^~~~~~~~~~~~~~~~~
../source/i18n/unicode/listformatter.h:34:7: note: forward declaration of 'icu_68::FormattedListData'
class FormattedListData;
      ^
```

The reason is that the `FormattedListData` class is compiled out when `UCONFIG_NO_FORMATTING=1` is defined. The fix is to compile out the `FormattedListBuilder` class as well in that case.